//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousePriceCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceChanx
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public Nullable<double> Change { get; set; }
        public int BoroughId { get; set; }
    
        public virtual Borough Borough { get; set; }
    }
}
